### ISSUE TITLE
Lookup by class (instead of name) doesn't use fully qualified name

### ISSUE THREAD

**Issue by pauleveritt** [mmerickel/wired#1]
I just did this in a test and was surprised it passed:

```python
# from wired.samples.simple_factory import Greeter
class Greeter:
    pass
factory = registry.find_factory(Greeter)
```

I have a registry with wired.samples.simple_factory.Greeter registered. I made a local Greeter, expecting it to fail on lookup. It passed. 

It appears `wired` only uses the class name, thus two different classes, same name but different modules/packages, would be considered "the same".

**Comment by mmerickel** [comment]
Thanks! I released 0.1.2 with a fix for this.

**Comment by pauleveritt** [comment]
I should have mentioned...let me fix things like this. :)

**Comment by mmerickel** [comment]
Oh sorry! The class-based stuff is a source of frustration for me in zope since it doesn't support using classes directly. I was embarrassed that my hacky code was broken!

**Comment by pauleveritt** [comment]
Though I might not have gotten the fix right, I could have submitted a test. My apologies.

Next up: provide better traceback messages when a lookup fails. `wired` doesn't say which lookup fails.
