### ISSUE TITLE
Why is it forbidden to set service for a custom context if service for a default context is set?

### ISSUE THREAD

**Issue by enkidulan** [mmerickel/wired#13]
I've been looking at tests and found `test_override_cache_via_set_fails` test:
https://github.com/mmerickel/wired/blob/c946ef473bb8b7a75856247a7c92c3443874dc6a/tests/test_container.py#L175-L182

I don't understand why it's not Okay to set a `service` for a custom `context` if a `service` for the default `context` is set. What is mean is that I don't understand why following code should fail:
```python
class Service:
    pass

registry.register_factory(lambda c: Service(), Service)
c = registry.create_container()
assert c.get(Service)

service2 = Service()
c.set(service2, Service, context='my_context')  # would rise a `ValueError` exception
```

**Comment by mmerickel** [comment]
This should be fixed in #14 where `.set` now operates on a specific context.
