### ISSUE TITLE
Dataclasses: Put a category on the scanner

### ISSUE THREAD

**Issue by pauleveritt** [mmerickel/wired#22]
As [discussed on the PR](19#discussion_r292156808) Michael said to change the `venusian` scanner to pass along a category.

**Comment by mmerickel** [comment]
To be clear my suggestion was to register the decorator for a specific category so that in the future a user could, if they choose, scan only those decorators. My comment was on the `attach`, not on the `scan`.

**Comment by pauleveritt** [comment]
Done.
