### ISSUE TITLE
Dataclasses: Context, Request, Resource

### ISSUE THREAD

**Issue by pauleveritt** [mmerickel/wired#25]
As [discussed on the pull request](19#discussion_r292160513) Michael zero'd in on my confusion about what I want for context. This ticket is a place to discuss it.

Let's say I want a `FrenchView` that's used when the current url (i.e. `Request`) points to a `FrenchCustomer`. In regular `wired` this would be:

```python
registry.register_factory(
        french_view_factory, View, context=FrenchCustomer
    )
```

Inside `FrenchView` you'd call some service, perhaps `CustomerService`, that would retrieve for you the `FrenchCustomer` instance. It would do so using information in the `Request`, i.e. `request.url`.

But do you really need to write a conext-fetching service for each kind of thing?

I was hoping to have a single `Context` service. It could look at the URL, go to the database, and return an instance. Just like a context factory in Pyramid. My examples went that route but were clumsy.

Michael suggested just presuming that something outside of the injector would start the request process by assigning the context to the container, using `registry.create_container(context=...)`. And thus `container.context` would, in the case above, have a `FrenchCustomer` instance.

In that case, you want a pluggable app that lets people customize database access. So let's say `wired.dataclasses` looks for a `Context` factory, which uses the request information to assign a context to the container (I might have that wrong.)

At that point, this should work:

```python
@factory(for_=View, context=FrenchCustomer)
@dataclass
class FrenchView:
    customer: FrenchCustomer = injector(Context)
    ### Or, less magically
    customer: FrenchCustomer = injector(Container, attr='context')
```

Last question: `Context` vs. `Resource`. Should they be the same thing? Or should a `Resource` be a certain kind of `Context` (similar to location-aware resource tree stuff in Pyramid)?

**Comment by mmerickel** [comment]
When wired talks about a context it is for a specific factory lookup. It is answering the question “find a factory that will return an instance of this type for this context”. I point this out because ultimately it matters who is doing the lookup. Can you make that part more clear? Where is the invocation `container.get(View, ...)`? Would the context be passed in to that call? Or would the container be bound to it already?

**Comment by mmerickel** [comment]
I think resource and context are basically the same in this discussion. The resource object is the context for the lookup.

**Comment by pauleveritt** [comment]
> When wired talks about a context it is for a specific factory lookup.

I'm obviously bringing in a bunch of historical baggage from Pyramid. Would you say wired's use of `context` matches Pyramid? In particular the idea of a "root factory" which grabs the data needed for a view, and then lets views get registered against data instead of routes?

That's basically what I'm trying to accomplish.

**Comment by pauleveritt** [comment]
> I think resource and context are basically the same in this discussion.

In Pyramid there are cases where the context isn't a resource, IIRC. E.g. exception views. Should I not care?

Perhaps I should avoid overloading wired's `context` and stick to `resource` as a new thing whose semantics match the kind of "root factory" I'm looking for?

**Comment by mmerickel** [comment]
I’d have to see an example where it clashes. Wired’s lookup is not nearly as complicated as Pyramid’s intentionally.

**Comment by pauleveritt** [comment]
> Where is the invocation container.get(View, ...)? Would the context be passed in to that call? 

Here's the [first spot in the injector's code](https://github.com/pauleveritt/wired/blob/dataclasses/src/wired/dataclasses/injector.py#L66) which does a `container.get` with context lookup. 

That loop is a very dodgy bit of work. Very brittle, has a bunch of policies in it and will have a couple more when I'm done. The unit tests and the comments are the only hope.

**Comment by mmerickel** [comment]
To be clear using wired for something as complex as view lookup is not something I ever imagined. Service layers are its bread and butter and lookups there are much more sane.

**Comment by pauleveritt** [comment]
You're right, this is getting complex. I propose I don't do any radical re-invention. Instead:

- I'll stick to saying `context`, since ultimately it's the value of the context argument
- For this DI system, people can register a `Context` factory
- `wired.dataclasses` will use that factory when constructing a container, and thus `container.context` will be there automatically
- A dataclass can get the current context with `context: Context`
- Or, more type-friendly, `customer: FrenchCustomer = injector(Context)`

**Comment by mmerickel** [comment]
You’re linking me library code which should for the most part not be using the context at all. Somewhere in user code should be a `.get` call with a context which is bound and used throughout the lookup without you needing to really bother with it.

**Comment by mmerickel** [comment]
Let me come up with an example of what I’m trying to describe about how wired properly handles the context already automatically. I’ll get back to you in a few minutes.

**Comment by mmerickel** [comment]
```python
@dataclass
class TypeA:
    b: TypeB

@dataclass
class TypeB:
    c: TypeC

@dataclass
class TypeC:
    pass

class Context1:
    pass

def factory_a(container):
    assert isinstance(container.context, Context1)
    return TypeA(b=container.get(TypeB))

def factory_b(container):
    assert isinstance(container.context, Context1)
    return TypeB(c=container.get(TypeC))

def factory_c(container):
    assert container.context is None
    return TypeC()

registry = ServiceRegistry()
registry.register_factory(factory_a, TypeA, context=Context1)
registry.register_factory(factory_b, TypeB, context=Context1)
registry.register_factory(factory_c, TypeC, context=None)

container = registry.create_container(context=Context1())
a = container.get(TypeA)
b = container.get(TypeB)  # <-- note the assertion in factory_b that context is set
c = container.get(TypeC)  # <-- note the assertion in factory_c that context is None
assert a.b is b
assert b.c is c

ctx2 = Context1()
a2 = container.get(TypeA, context=ctx2)
assert a2 is not a
assert a2.b is not b
assert a2.b.c is c    # <-- note the c is equal
```

**Comment by mmerickel** [comment]
Compare the example above to the code in your `Injector` class... none of the factories above really care about context - it's just forwarded through between calls to `container.get()`. What matters is what the original context is when the user-code calls `get()` either via `get(context=...)` or by using the bound context of the container. Wired then passes it through factories unless you choose to override it for a subtree explicitly for some reason - but the default is that the factories do not pass it around explicitly.

**Comment by pauleveritt** [comment]
Yep, this is good stuff and will likely be a notable simplification. `registry.create_container(context=Context1())` is the bit I wasn't thinking about. Thanks!

**Comment by pauleveritt** [comment]
Done.
