### ISSUE TITLE
Get alternate version of auto doc to allow bringing back api.rst docs of injected

### ISSUE THREAD

**Issue by pauleveritt** [mmerickel/wired#28]
Adding injected to `api.rst` results in:

```
error while formatting arguments for wired.dataclasses.injected: 'function' object has no attribute '__mro__'
262
```

...during the building of sphinx docs.  There's an alternative to autodoc out there that fixes it.

**Comment by mmerickel** [comment]
this appears to be fixed, I added docs for injected, and a few others in https://github.com/mmerickel/wired/commit/6f47030e3a5ff1c2030083ef3e1a6cd3505ce345 and it is rendering well.
